### ISSUE TITLE
Unicode errors

### ISSUE THREAD

**Issue by okainov** [grantmcconnaughey/django-chartit2#3]
This is kind a copy of issue #5 in original repo https://github.com/pgollakota/django-chartit/issues/5

The library raises error when there is unicode data in x-axis labels (or maybe in some other cases)
Iэму found a workaround which is pretty simple: replace line 531 from chartdata.py
 `lv = tuple(map(str, lv))`
to
`lv = tuple(map(unicode, lv))`

Please take a look, maybe this solution will work for production code.

**Comment by atodorov** [comment]
You can close this. Will be resolved in chartit#5.

@GodfatherThe - fyi I've merged back django-chartit2 into django-chartit and a new release on PyPI will be due soon. Cleaning up some stuff atm.
