### ISSUE TITLE
TypeError: 'dict_keys' object does not support indexing

### ISSUE THREAD

**Issue by nikepan** [grantmcconnaughey/django-chartit2#5]
File ".../django_chartit2-0.2.2-py3.4.egg/chartit/charts.py", line 533, in set_default_hcoptions
categories = dss[terms[0]]['categories']
TypeError: 'dict_keys' object does not support indexing

need modify:

```
charts.py [517]:
terms = self.series_options.keys()
to:
terms = list(self.series_options.keys())
```

**Comment by grantmcconnaughey** [comment]
Agreed. I'll try to get this changed soon. Or, if you'd like, feel free to submit a PR and I'll get it merged. Thanks!

**Comment by atodorov** [comment]
Fixed in:
https://github.com/chartit/django-chartit/commit/633f36439a909ecf6738ee085a11b54d9998bb2f

@grantmcconnaughey - you can close this.

@nikepan: I've merged back django-chartit2 into django-chartit and a new release on PyPI will be due soon. Cleaning up some stuff atm.
